spring.application.name=api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/marcando_huellitas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root


spring.datasource.password=Delleve
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

