spring.application.name=api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/marcando_huellitas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root


spring.datasource.password=Pelusa01?
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# CONFIGURACION CORREO (Gmail SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=marcandohuellitas100@gmail.com
spring.mail.password=rnubzmtvrjcyxdgd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
